### DISCUSSION TITLE
白名单有更方便的方式来批量添加吗?

### DISCUSSION THREAD

**Discussion by Jonnyan404** [chanify/chanify#47] [Q&A]
现有的添加白名单方式,有点限制死了,假设用docker部署,如果我要添加白名单,就得干掉镜像,重启一个,每次修改和添加都很不方便.
是否可以通过配置文件来配置?

**Comment by wizjin** [comment]
在yml的配置文件中可以配置，用docker的话默认在`/root/.chanify.yml`。要想修改文件位置的话可以使用参数`--config`。

```yml
server:
    register:
        enable: false
        whitelist:
            - <user id 1>
            - <user id 2>
            ...
```

但是目前修改配置文件后需要重启服务才会reload这个文件。
