### ISSUE TITLE
feat: 感谢大佬的Chanify

### ISSUE THREAD

**Issue by i-iooi-i** [chanify/chanify#111]
终于把Chanify在群晖上配置成功。

比较小白，使用群晖自带的Docker界面配置的，然后 http://192.168.1.100:9070/  确实也打开了二维码的图片，在与群晖同一个局域网里使用手机端扫描二维码图片的时候，提示：无法连接服务器。查看日志有一处显示： endpoint=http://0.0.0.0:9070。

后来使用Portainer执行了一下 command: serve --name=<nas> --endpoint=http://192.168.100.1:9070 才算成功。😂

不太懂代码，若是方便的话，希望大佬在Docker的环境变量里能预留出一个配置内网IP地址的地方，要不然像我这类小白真的要钻研很久很久。😂 也算是方便更多后来人使用Chanify啦，再次感谢大佬~~

**Comment by akimolll** [comment]
![2022-03-01 01 04 12](https://user-images.githubusercontent.com/1827701/156026696-3a7bf630-38c1-4645-a732-137f78d2d24a.png)

另外就在刚才的使用中发现了一个问题，
当在Google中搜索英文的时候，推送的链接是正确的。
当使用Google搜索中文的时候，推送到手机的链接会是乱码。

**Comment by wizjin** [comment]
@akimolll 配置文件里面可以配置，或者通过参数，暂时不支持环境变量。

中文的时候不是乱码，是 url 转义了。你是用什么发送这个消息的。

**Comment by akimolll** [comment]
![Snipaste_2022-03-01_12-55-49](https://user-images.githubusercontent.com/1827701/156107650-2c47550b-bf95-4e68-bd9b-f21cd582f485.png)

起初我是用群晖的面板界面手动配置的，然后无法找到配置内网IP地址的地方。
于是又去看一位博主的文章 ，如上图，终于配置成功了。
博主配置如下：
```
version: '3'

services:
  chanify:
    image: wizjin/chanify:latest
    container_name: chanify
    restart: always
    volumes:
      - ./data:/root/.chanify
    ports:
      - "9070:80"
    command: serve --name=<nas> --endpoint=http://192.168.192.1:9070
```

成功之后，我也试着去映射 my/config.yml:/root/.chanify.yml 这个文件到本地，但是会导致Dorker启动失败，无法把这个文件映射到本地。因此在文件夹里看不到这个配置文件。

**Comment by akimolll** [comment]
![Snipaste_2022-03-01_13-13-18](https://user-images.githubusercontent.com/1827701/156109156-efa36ee2-c429-40f2-a924-e88a28242312.png)

消息推送是用chrome的插件，上面截了个图方便查看。以上~

**Comment by wizjin** [comment]
你的data目录和chanify.yml冲突了，试着分开配置就能启动了
```yml  
      volumes:
            - ./data:/data
            - ./chanify.yml:/root/.chanify.yml
```

对于网页，你点击搜索条目发送单独的链接应该是好的，发送页面我回头看一下。

**Comment by akimolll** [comment]
感谢大佬回复。

![Snipaste_2022-03-01_14-22-35](https://user-images.githubusercontent.com/1827701/156116867-16a8c09c-e2f1-4053-8888-0fd4212a6fce.png)
再来跟大佬同步一下问题，我试着这样去运行。👆

![Snipaste_2022-03-01_14-23-20](https://user-images.githubusercontent.com/1827701/156117020-c6db6937-a6c7-4163-821f-c5f48ab3672c.png)
运行完成之后，Docker界面显示无法启动。

![Snipaste_2022-03-01_14-25-06](https://user-images.githubusercontent.com/1827701/156117101-464e994e-4843-45f7-a711-b2f4bb741880.png)

于是我试着上传一个0字节的chanify.yml文件 / 也尝试在这个chanify.yml粘贴配置 / 也试着去删掉这个chanify.yml希望可以映射出来 / 然而Docker都是报错的。

![Snipaste_2022-03-01_14-25-06](https://user-images.githubusercontent.com/1827701/156117428-543c701b-a6d9-4f34-9d67-fbe9eafa5737.png)
另外我不管用哪种方式去映射，这个data目录下始终都是空的~

反倒是之前用博主的  
```
volumes:
      - ./data:/root/.chanify
```
能正常启动Docker，而且也能映射出存放文件的几个文件夹。而美中不足的就是无法映射出.yml这个配置文件。

**Comment by wizjin** [comment]
`chanify.yml` 文件里面要有配置才可以，启动不起来所以 data 是空的。

```yml
      volumes:
            - /volume1/docker/Chanify/data:/data
            - /volume1/docker/Chanify/chanify.yml:/root/.chanify.yml
```

chanify.yml文件中至少配置：
```yml
server:
    host: 0.0.0.0
    port: 8080
    endpoint: http://192.168.1.100:9070
    name: zolo
    datapath: /data
```
