### ISSUE TITLE
Init service failed: In serverless mode, secret is required

### ISSUE THREAD

**Issue by Jonnyan404** [chanify/chanify#38]
使用配置文件的方式,会一直提示标题这个错误,要怎么解决啊?

`chanify serve  --config=/opt/chanify.yml`

```
server:
    host: 0.0.0.0
    port: 10000
    endpoint: https://xxx.xxx.fun
    name: apple

```

配置文件增加  `serverless: false` 也不行

**Comment by wizjin** [comment]
缺少`datapath`字段

```yml
server:
    host: 0.0.0.0
    port: 10000
    endpoint: https://xxx.xxx.fun
    name: apple
    datapath: /opt/chanify
```
